language: elixir

sudo: false

elixir:
  - 1.6

otp_release:
  - 21.0

branches:
  only:
    - master

env:
  - MIX_ENV=test

script:
  - mix dialyzer --list-unused-filters --halt-exit-status
  - mix coveralls.travis

cache:
  directories:
    - priv/plts
